[package]
name = "todo_list"
version = "0.5.0"
edition = "2021"

[dependencies]
tui = "0.18"
crossterm = "0.23"
unicode-width = "0.1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }